name: Create Branch Protection Ruleset

on:
  workflow_dispatch: 

jobs:
  create-ruleset:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up variables
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          TOKEN: ${{ secrets.REPO_ADMIN_TOKEN }}

      - name: Load Branch Protection Rules JSON
        id: load-rules
        run: |
          RULESET_BODY=$(<.github/workflows/branch-rules.json)
          echo "RULESET_BODY=$RULESET_BODY" >> $GITHUB_ENV

      - name: Apply Branch Protection Ruleset
        run: |
          BRANCHES=("main" "prpd" "dev")
          
          for BRANCH in "${BRANCHES[@]}"; do
            echo "Applying branch protection to $BRANCH..."
            
            curl -X PUT -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH/protection \
              -d "$RULESET_BODY"
          done
